name = "akms-kinder-management"
type = "javascript"
account_id = ""
workers_dev = true
routes = []
zone_id = ""

[env.production]
name = "akms-production"

[build]
cwd = "frontend"
command = "npm run build"
watch_paths = ["src/**/*.ts", "src/**/*.tsx"]

[build.upload]
format = "service-worker"
main = ""

[env.production.build]
cwd = "frontend"
command = "npm run build"
