/**
 * VideoAnalysisContext - 비디오 기반 행동 분석
 * Phase 5 Stream P2.2
 *
 * - 비디오 업로드 & 저장 시스템
 * - 프레임 단위 행동 인식
 * - 자동 ABC 기록 생성
 */

import React, { createContext, useContext, useState, useCallback } from 'react';
import { VideoAnalysisResult, VideoSession } from '../types';

interface IVideoAnalysisContext {
  videoSessions: VideoSession[];
  analysisResults: VideoAnalysisResult[];
  uploadVideo: (file: File, childId: number, ltoId: string) => Promise<string>;
  startAnalysis: (videoId: string) => Promise<void>;
  getAnalysisResult: (videoId: string) => VideoAnalysisResult | undefined;
  deleteVideo: (videoId: string) => void;
  getVideoSessions: (childId: number) => VideoSession[];
  generateABCFromAnalysis: (analysisId: string) => Promise<any>;
}

const VideoAnalysisCtx = createContext<IVideoAnalysisContext | undefined>(undefined);

export function VideoAnalysisProvider({ children }: { children: React.ReactNode }) {
  const [videoSessions, setVideoSessions] = useState<VideoSession[]>([]);
  const [analysisResults, setAnalysisResults] = useState<VideoAnalysisResult[]>([]);

  const uploadVideo = useCallback(async (file: File, childId: number, ltoId: string): Promise<string> => {
    try {
      // 실제 구현에서는 서버에 업로드
      const videoUrl = URL.createObjectURL(file);
      const videoId = `video_${Date.now()}`;

      const newSession: VideoSession = {
        id: videoId,
        childId,
        ltoId,
        videoUrl,
        duration: 0,
        uploadedBy: 'current_user',
        uploadedAt: new Date().toISOString(),
        status: 'active',
      };

      setVideoSessions(prev => [...prev, newSession]);
      return videoId;
    } catch (error) {
      console.error('Failed to upload video:', error);
      throw error;
    }
  }, []);

  const startAnalysis = useCallback(async (videoId: string) => {
    try {
      const session = videoSessions.find(v => v.id === videoId);
      if (!session) throw new Error('Video session not found');

      // 프레임 단위 분석 시뮬레이션
      const analysisResult: VideoAnalysisResult = {
        id: `analysis_${Date.now()}`,
        childId: session.childId,
        videoUrl: session.videoUrl,
        uploadedAt: session.uploadedAt,
        duration: 300, // 5분 예시
        frames: generateMockFrames(),
        analysis: {
          behaviorSummary: [
            { behavior: '앉기', occurrences: 45, totalDuration: 240, averageConfidence: 0.92 },
            { behavior: '눈맞춤', occurrences: 38, totalDuration: 180, averageConfidence: 0.85 },
          ],
          autoGeneratedABC: {
            antecedent: '치료사가 "앉으세요" 지시',
            behavior: '아동이 자리에 앉음',
            consequence: '칭찬 및 강화물 제공',
            confidence: 0.88,
          },
          overallAccuracy: 88,
          independenceRating: 'partial',
        },
        processingStatus: 'completed',
        processedAt: new Date().toISOString(),
        createdAt: new Date().toISOString(),
      };

      setAnalysisResults(prev => [...prev, analysisResult]);
    } catch (error) {
      console.error('Failed to start analysis:', error);
      throw error;
    }
  }, [videoSessions]);

  const getAnalysisResult = useCallback((videoId: string) => {
    return analysisResults.find(r => r.id === videoId);
  }, [analysisResults]);

  const deleteVideo = useCallback((videoId: string) => {
    setVideoSessions(prev => prev.filter(v => v.id !== videoId));
    setAnalysisResults(prev => prev.filter(r => r.id !== videoId));
  }, []);

  const getVideoSessions = useCallback((childId: number) => {
    return videoSessions.filter(v => v.childId === childId);
  }, [videoSessions]);

  const generateABCFromAnalysis = useCallback(async (analysisId: string) => {
    const result = analysisResults.find(r => r.id === analysisId);
    if (!result || !result.analysis.autoGeneratedABC) {
      throw new Error('Analysis result not found or no ABC generated');
    }

    const abc = result.analysis.autoGeneratedABC;
    return {
      id: `abc_${Date.now()}`,
      childId: result.childId,
      ltoId: 'lto_1', // 실제로는 결정해야 함
      antecedent: {
        type: 'instruction' as const,
        description: abc.antecedent,
        context: '세션 중',
      },
      behavior: {
        targetBehavior: abc.behavior,
        responseType: 'correct' as const,
        latency: 2,
        accuracy: result.analysis.overallAccuracy,
        dataPoints: {
          trials: 45,
          correctTrials: 40,
          accuracy: result.analysis.overallAccuracy,
          independenceLevel: result.analysis.independenceRating,
        },
      },
      consequence: {
        type: 'reinforcement' as const,
        reinforcementType: 'social' as const,
        description: abc.consequence,
      },
      createdAt: new Date().toISOString(),
    };
  }, [analysisResults]);

  const value: IVideoAnalysisContext = {
    videoSessions,
    analysisResults,
    uploadVideo,
    startAnalysis,
    getAnalysisResult,
    deleteVideo,
    getVideoSessions,
    generateABCFromAnalysis,
  };

  return (
    <VideoAnalysisCtx.Provider value={value}>
      {children}
    </VideoAnalysisCtx.Provider>
  );
}

export function useVideoAnalysis() {
  const context = useContext(VideoAnalysisCtx);
  if (!context) {
    throw new Error('useVideoAnalysis must be used within VideoAnalysisProvider');
  }
  return context;
}

function generateMockFrames() {
  const frames = [];
  for (let i = 0; i < 300; i++) {
    frames.push({
      frameNumber: i,
      timestamp: i,
      behaviorDetected: Math.random() > 0.3 ? ['앉기', '눈맞춤'] : ['앉기'],
      confidence: 0.80 + Math.random() * 0.2,
      keypoints: [
        { x: 100 + Math.random() * 50, y: 150 + Math.random() * 50, label: '머리' },
        { x: 120 + Math.random() * 50, y: 200 + Math.random() * 50, label: '몸' },
      ],
    });
  }
  return frames;
}
